name: Create PR/Release build
on:
  pull_request_target:
    types: [opened, synchronize]
  branches: "main"
  push:
    tags:
      - "*"

jobs:
  build_addon_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head # If its a PR we wanna build from the head of the PR branch
        if: github.event.pull_request.base.ref == 'main'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout main # If its a release tag we wanna build from the main branch
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/checkout@v4
      # This next bit is to create a dir that has all the development related stuff stripped
      # Basically we want our releases to only contain stuff that wow needs
      - name: Create Artifact dir
        run: mkdir bossMogsAddon
      - name: Read blacklist and copy files
        shell: bash
        run: |
          dest_dir="addonArtifact"

          shopt -s globstar dotglob nullglob

          mapfile -t blacklist < .blacklist

          for file in **/*; do
            skip=false
            for blockedFile in "${blacklist[@]}"; do
              if [[ "$item" == "$blockedFile" ]]; then
                skip=true
                echo "Skipping file as it is blacklisted: $item"
                break
              fi
            done

            if [ "$skip" = false ]; then
              dest_path="$dest_dir/$src_file"
              mkdir -p "$(dirname "$dest_path")"
              cp "$src_file" "$dest_path"
            fi
          done
      - name: Upload artifact on PR
        uses: actions/upload-artifact@v4
        if: github.event.pull_request.base.ref == 'main'
        with:
          name: BossMogs
          path: addonArtifact/
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event.pull_request.base.ref == 'main'
        with:
          name: BossMogs
          path: addonArtifact/
